notifications:
  email:
    recipients:
      - hussama.ismail@gmail.com
    on_success: always
    on_failure: always

language: c

sudo: required

#compiler:
#  - clang
#  - gcc

#os:
#  - linux
#  - osx

#arch:
#  - amd64

before_install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test && sudo apt-get -qq update && sudo apt-get install xsltproc; fi  

#stages:
#  - name: "Tests on AMD64 (gcc)"
#  - name: "Tests on ARM64 (clang)"
  
jobs:
  include:
    - stage: "Tests on AMD64 (linux)"
      script: make generic64/UnitTests && bin/generic64/UnitTests -a
      os: linux
      arch: amd64
      compiler: gcc
      name: "generic64 (gcc)"
    - script: make generic64/UnitTests && bin/generic64/UnitTests -a
      os: linux
      arch: amd64
      compiler: clang
      name: "generic64 (clang)"
    - script: make asmX86-64/UnitTests && bin/asmX86-64/UnitTests -a
      os: linux
      arch: amd64
      compiler: gcc
      name: "asmX86-64 (gcc)"
    - script: make asmX86-64/UnitTests && bin/asmX86-64/UnitTests -a
      os: linux
      arch: amd64
      compiler: clang
      name: "asmX86-64 (clang)"
    - script: make asmX86-64shld/UnitTests && bin/asmX86-64shld/UnitTests -a
      os: linux
      arch: amd64
      compiler: gcc
      name: "asmX86-64shld (gcc)"
    - script: make asmX86-64shld/UnitTests && bin/asmX86-64shld/UnitTests -a
      os: linux
      arch: amd64
      compiler: clang
      name: "asmX86-64shld (clang)"
    - script: make Nehalem/UnitTests && bin/Nehalem/UnitTests -a
      os: linux
      arch: amd64
      compiler: gcc
      name: "Nehalem (gcc)"
    - script: make Nehalem/UnitTests && bin/Nehalem/UnitTests -a
      os: linux
      arch: amd64
      compiler: clang
      name: "Nehalem (clang)"
    - script: make SandyBridge/UnitTests && bin/SandyBridge/UnitTests -a
      os: linux
      arch: amd64
      compiler: gcc
      name: "SandyBridge (gcc)"
    - script: make SandyBridge/UnitTests && bin/SandyBridge/UnitTests -a
      os: linux
      arch: amd64
      compiler: clang
      name: "SandyBridge (clang)"
    - script: make Haswell/UnitTests && bin/Haswell/UnitTests -a
      os: linux
      arch: amd64
      compiler: gcc
      name: "Haswell (gcc)"
    - script: make Haswell/UnitTests && bin/Haswell/UnitTests -a
      os: linux
      arch: amd64
      compiler: clang
      name: "Haswell (clang)"
      #script: make SkylakeX/UnitTests && bin/SkylakeX/UnitTests -a # not supported yet
      #name: "SkylakeX"                                             # not supported yet

#script:
#  - make generic64/UnitTests && bin/generic64/UnitTests -a
#  - make asmX86-64/UnitTests && bin/asmX86-64/UnitTests -a
#  - make asmX86-64shld/UnitTests && bin/asmX86-64shld/UnitTests -a
#  - make Nehalem/UnitTests && bin/Nehalem/UnitTests -a
#  - make SandyBridge/UnitTests && bin/SandyBridge/UnitTests -a
#  - make Haswell/UnitTests && bin/Haswell/UnitTests -a
#  - make SkylakeX/UnitTests && bin/SkylakeX/UnitTests -a
