notifications:
  email:
    recipients:
      - hussama.ismail@gmail.com
    on_success: always
    on_failure: always

language: c

sudo: required

compiler:
  - clang
  - gcc

os:
  - linux
  - osx

arch:
  - amd64

before_install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test && sudo apt-get -qq update && sudo apt-get install xsltproc; fi

script:
  - make generic64/KeccakTests && ./bin/generic64/KeccakTests --all
